#!/bin/sh

#
# Vagrant Windows box factory
#
# @author Luke Carrier <luke@carrier.im>
# @copyright 2015 Luke Carrier
# @license GPL v3
#

ROOT_DIR="$(dirname $(readlink -fn $0))"
CACHE_DIR="${ROOT_DIR}/cache"

mkdir -p "$CACHE_DIR"

# SQL Server 2008 R2 SP2 - Express Edition
#
# http://www.microsoft.com/en-gb/download/details.aspx?id=30438
SQL_SERVER_2008_R2_ADV_64="http://download.microsoft.com/download/0/4/B/04BE03CD-EAF3-4797-9D8D-2E08E316C998/SQLEXPRADV_x64_ENU.exe"

# PHP Manager for IIS
#
# https://phpmanager.codeplex.com/releases/view/69115
PHP_MANAGER_IIS_64="http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=phpmanager&DownloadId=253209&FileTime=129536821813970000&Build=20983"

# PHP 5.5 NTS VC11 x86 build (currently 5.5.23)
#
# http://windows.php.net/download/
PHP_55="http://windows.php.net/downloads/releases/php-5.5.24-nts-Win32-VC11-x86.zip"

if [ ! -f "${CACHE_DIR}/SQLEXPRADV_x64_ENU.exe" ]; then
    curl --location --output "${CACHE_DIR}/SQLEXPRADV_x64_ENU.exe" \
         "$SQL_SERVER_2008_R2_ADV_64"
fi

if [ ! -f "${CACHE_DIR}/PHPManagerForIIS-1.2.0-x64.msi" ]; then
    curl --location --output "${CACHE_DIR}/PHPManagerForIIS-1.2.0-x64.msi" \
         "$PHP_MANAGER_IIS_64"
fi

if [ ! -f "${CACHE_DIR}/php-5.5.24-nts-vc11-x86.zip" ]; then
    curl --location --output "${CACHE_DIR}/php-5.5.24-nts-vc11-x86.zip" "$PHP_55"
fi
