#!/bin/sh

#
# Vagrant Windows box factory
#
# @author Luke Carrier <luke@carrier.im>
# @copyright 2015 Luke Carrier
# @license GPL v3
#

ROOT_DIR="$(dirname $(readlink -fn $0))"
CACHE_DIR="${ROOT_DIR}/cache"

mkdir -p "$CACHE_DIR"

# SQL Server 2008 R2 SP2 - Express Edition
#
# http://www.microsoft.com/en-gb/download/details.aspx?id=30438
SQL_SERVER_2008_R2_ADV_64="http://download.microsoft.com/download/0/4/B/04BE03CD-EAF3-4797-9D8D-2E08E316C998/SQLEXPRADV_x64_ENU.exe"

# PHP Manager for IIS
#
# https://phpmanager.codeplex.com/releases/view/69115
PHP_MANAGER_IIS_64="http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=phpmanager&DownloadId=253209&FileTime=129536821813970000&Build=20988"

# PHP 5.5 NTS VC11 x86 build (currently 5.5.23)
#
# http://windows.php.net/download/
PHP_55="http://windows.php.net/downloads/releases/php-5.5.24-nts-Win32-VC11-x86.zip"

# .NET Framework 4 (Standalone Installer)
#
# https://www.microsoft.com/en-gb/download/details.aspx?id=17718
DOTNET_40="http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe"

# Windows Management Framework 3.0
#
#https://www.microsoft.com/en-gb/download/details.aspx?id=34595
WMF_30="http://download.microsoft.com/download/E/7/6/E76850B8-DA6E-4FF5-8CCE-A24FC513FD16/Windows6.1-KB2506143-x64.msu"

if [ ! -f "${CACHE_DIR}/SQLEXPRADV_x64_ENU.exe" ]; then
    curl --location --output "${CACHE_DIR}/SQLEXPRADV_x64_ENU.exe" \
         "$SQL_SERVER_2008_R2_ADV_64"
fi

if [ ! -f "${CACHE_DIR}/PHPManagerForIIS-1.2.0-x64.msi" ]; then
    curl --location --output "${CACHE_DIR}/PHPManagerForIIS-1.2.0-x64.msi" \
         "$PHP_MANAGER_IIS_64"
fi

if [ ! -f "${CACHE_DIR}/php-5.5.24-nts-vc11-x86.zip" ]; then
    curl --location --output "${CACHE_DIR}/php-5.5.24-nts-vc11-x86.zip" "$PHP_55"
fi

if [ ! -f "${CACHE_DIR}/Windows6.1-KB2506143-x64.msu" ]; then
    curl --location --output "${CACHE_DIR}/Windows6.1-KB2506143-x64.msu" "$WMF_30"
fi

if [ ! -f "${CACHE_DIR}/dotNetFx40_Full_x86_x64.exe" ]; then
    curl --location --output "${CACHE_DIR}/dotNetFx40_Full_x86_x64.exe" "$DOTNET_40"
fi
